### ISSUE TITLE
About the planned formatting implementations

### ISSUE THREAD

**Issue by mariogarcc** [Jelomite/horrible-downloader#10]
I tried to make a little something to maybe help you implement those things, although I don't really know how the script works, so I don't know if you can make any use (and I can't make a PR) out of this. Hopefully it'll be enough to at least give you an idea or a clue on how to do it yourself.

```python
# Cases:
# 1: Commas and dashes: 1, 2, 3, 4 - 6
# 2: Greater/lower than: 7> (or) <10
# 3: 2, plus equal sign: 7>=
# 4?: Adding commas inbetween: <=10, 14>=

# Let `ep_str` be the string containing the episode numbers information
# each case variable below would correspond to the abovementioned `ep_str`

import re

case_1 = "1, 2, 3, 4 - 6, 7, 8"
case_21 = "7>"
case_22 = "<10"
case_3 = "7>="
case_4 = "<=10, 14>="

cases = [case_1, case_21, case_22, case_3, case_4]

groups_re = r"([\d\-\<\>\=\s]+)(?:\s*\,?\s*)"
# (I suggest to) remove \s in the first group if you do not want to accept "4 - 6" or "< 7" as valid syntax
# groups_re = r"([\d\-\<\>\=]+)(?:\s*\,?\s*)" # It would be like this

for case in cases:

    exp_groups = re.findall(groups_re, case)

    ep_nums = []

    for group in exp_groups:

        if group.isdigit():
            ep_num = int(group)
            ep_nums += [ep_num]

        else:

            if '-' in group:
                ep_num_1 = int(re.search(r"(\d+)", group).group(1))
                ep_num_2 = int(re.search(r"(?:\-\s*)(\d+)", group).group(1))
                ep_nums += list(range(ep_num_1, ep_num_2 +1))

            elif '<' in group:
                ep_num = int(re.search(r"(\d+)", group).group(1))
                ep_nums += list(range(1, ep_num))
                if '=' in group:
                    ep_nums += [ep_num]
                
            elif '>' in group:
                ep_num = int(re.search(r"(\d+)", group).group(1))
                if '=' in group:
                    ep_nums += [ep_num]
                # find max episode number for that show
                max_episode_num = 25 # just for the example
                ep_nums += list(range(ep_num +1, max_episode_num +1))

    print(ep_nums)

# check if episode numbers appear more than once in the list
# or make a way to automatically remove the duplicates

# for episode in ep_nums:
#     download(episode) # or whatever

# Possible issues (depending on the site you're downloading from, I don't know):
# there may be an episode 0 (or that appears as 0 in the search).
# there may be episodes with non integer numbers (e.g. 13.5)
# there may be episodes with word titles
```
This is not very strict with the syntax in really any way but if you need it to be in fact strict, it's not hard to figure out either. I could do it in a couple minutes, so just say it if you need it like that.

**Comment by mtshrmn** [comment]
Currently, this is the [implementation](https://github.com/Jelomite/horrible-downloader/blob/6ee4c647307795422872a54ed2eba44b68188f7d/bin/horrible-downloader#L42): 
```py
def generate_episode_filter(episodes):
    """
    parse the episode specification string to generate a filter function.
    read the docs for understanding the syntax.
    :param episodes: the episode specification string
    :return: filter function for the episodes
    """
    # if no episodes where specified - the generated filter should return false.
    if not episodes:
        def default_filter():
            return False
        return default_filter

    parsed = []
    for token in episodes.split(","):
        sub = token.split("-")
        bounds = float(sub[0]), float(sub[int(len(sub) is 2)])
        parsed.append(bounds)

    def generated_filter(episode):
        return any(map(lambda bound: bound[0] <= float(episode["episode"]) <= bound[1], parsed))

    return generated_filter
```

I believe that introducing regex solely for this would be over engineering the solution.

**Comment by mariogarcc** [comment]
I understand writing that whole thing into that small code that actually works for the current state of the program may be a bit ugly, but here's my honest opinion. Although I'm not very good nor experienced at Python, after reading through the whole code, that part of it that you just showed me with lines 108 and 109 are the ones I understand the least (all those filters seem to me that are just a short way to make some exclusive comparisons, but to me are still non-inmediate). I see you know what you're doing, but maybe you're also trying too hard there to keep code extremely short at the cost of readability (and possibly functionality as well, about what we're mentioning).

I repeat, I really don't understand exactly everything that code is doing, but I kind of can see what you're going for and I think adding some lines of code to make everything more readable and even add more functionality would be a good idea. I'm not saying my implementation is the best - I'm sure you can find a better way to put it there in less or more organized lines - but it doesn't look like over engineering to me, even less when there's no current solution to compare it to.
