### ISSUE TITLE
Next week's episodes are downloading

### ISSUE THREAD

**Issue by Koussay-Akchi** [Jelomite/horrible-downloader#16]
i ran horrible downloader and it downloaded episode 10 of fire force and 11 of dr.stone(which air next week
of course they didn't download in my torrent client but i'm not sure if it's going to work next week

**Comment by mtshrmn** [comment]
This is very weird, please paste here your config.

**Comment by Koussay-Akchi** [comment]
i'm sorry but which file are you talking about?

**Comment by mtshrmn** [comment]
When you run the CLI for the first time, it generates a config file inside of `~/.config/horrible-downloader/conf.ini` (linux) or `C:\Users\USER\.config\horrible-downloader\conf.ini` (windows).
please paste the file here.

**Comment by mtshrmn** [comment]
No further discussion is being made. I'm closing this issue.

**Comment by Koussay-Akchi** [comment]
i'm so sorry for deserting this thread my internet didn't work for 2 days :(
i managed to fix it by manually changing the episode to start downloading from
don't know how the problem occured but it never happened again
