### ISSUE TITLE
Choose between different download methods

### ISSUE THREAD

**Issue by FlamingCupcake** [Jelomite/horrible-downloader#18]
Hey :)

It would be useful to add an option to choose download methods other than webtorrent.

I think this could be implemented pretty generically by replacing download() in cmd.py with a Downloader object, and then creating another class for each download method you want to implement, which the Downloader would then wrap.

I attached an example for the basic idea I have. If it's alright, I could implement it further :D

[downloader.py.txt](https://github.com/Jelomite/horrible-downloader/files/3704715/downloader.py.txt)
[example.py.txt](https://github.com/Jelomite/horrible-downloader/files/3704716/example.py.txt)

**Comment by mtshrmn** [comment]
This is a great feature to have. The only problem I have is getting a callback when an episode has finished downloading. When the download process is managed with python (at the current version), I simply block the main script when downloading, and when the download is done, the script is unblocked again and can update the downloaded file in it's config file. 

```py
# once this is done, only then the following part will continue
download(episode_obj, QUALITIES, abs_path)

# update the downloaded file in config
if not args.download:
    CONFIG.conf["subscriptions"][episode_obj["title"].lower()] = episode_obj["episode"].lstrip("0")
    with open(os.path.join(CONFIG.dir, CONFIG.file), "w") as f:
        CONFIG.conf.write(f)
```
With your idea, once the magnet is sent to a detached process, I have no control over it and I have no idea when the file has finished downloading. If you can find a solution for this, I'll be more than glad to add this.

**Comment by FlamingCupcake** [comment]
Specifically for Deluge, the call to add a magnet link returns a `torrent_id`, which can then be used with the `core.get_torrent_status` call to get the current state of the torrent. You could then use it like this:
```python
torrent_id = self.deluge.call('core.add_torrent_magnet', magnet_link, {'download_location': output_dir,})

torrent_status = self.deluge.call('core.get_torrent_status', torrent_id, ['state'])
while torrent_status[b'state'] != b'Seeding':
    time.sleep(3)
    torrent_status = self.deluge.call('core.get_torrent_status', torrent_id, ['state'])
```

**Comment by mtshrmn** [comment]
In that case, I think your implementation idea is good, and if you can implement it, ill add it. 
Sorry for not responding fast, I don't have access to a computer most of the time.

**Comment by mtshrmn** [comment]
Closed due to inactivity.
