### ISSUE TITLE
Running into exceptions while batch downloading

### ISSUE THREAD

**Issue by anshumanv** [Jelomite/horrible-downloader#19]
Hi! Amazing tool, I just tried downloading this anime's batch but ran into these issues, am I missing something?

Thanks!

I'm on MacOS Catalina, running zsh on iTerm2.

![image](https://user-images.githubusercontent.com/21009455/69119629-360ade00-0abd-11ea-92e5-46ab27ce3401.png)

**Comment by mtshrmn** [comment]
Thanks you for submitting an issue, this is clearly a bug. Unfortunately, I'll be able to fix it only on the weekend.

**Comment by mtshrmn** [comment]
This is now fixed, upgrade to version 1.0.4 to see the changes.

**Comment by anshumanv** [comment]
Great, thanks!
