### ISSUE TITLE
Possible to add multiples resolutions ? 

### ISSUE THREAD

**Issue by RGFRv2** [Jelomite/horrible-downloader#2]
Hi, 
I would like to know if it's possible to add the possibility to download with several resolutions at the same time ?

**Comment by mtshrmn** [comment]
Currently not, but I'll do so on the weekend.

**Comment by mtshrmn** [comment]
Check out the new [release](https://github.com/Jelomite/horrible-downloader/releases/tag/v0.1.3). I've implemented the new feature.
I didn't update the README yet, I'll do so later - the usage is as follows:

_In the command line:_
```bash
$ horrible-downloader -r 480,720,1080
```
_In the config file:_
```ini
[settings]
resolution = 480,720,1080
```
you can of course use only one resolution

I would love to hear some feedback :smile:

**Comment by RGFRv2** [comment]
Hello, 

This works with '-r' in the command but in the configuration file with :
```
[settings]
resolution = 480,720
```
or
```
resolution = 480,720,1080
```
It doesn't work, it shows me that: 
```
user@server:~/animes$ horrible-downloader -d Radiant -e 15 -o videos/
Invalid configuration file.
user@server:~/animes$
``` 
I also deleted the conf file to get a new one and add multiple resolutions but it gives the same result.

**Comment by mtshrmn** [comment]
There was a problem with the syntax validation, I haven't changed it to support multiple resolutions. Should work on the latest commit.
