### ISSUE TITLE
not work to python 3.5 syntax error

### ISSUE THREAD

**Issue by baxa73** [Jelomite/horrible-downloader#20]
Traceback (most recent call last):
  File "/usr/local/bin/horrible-downloader", line 7, in <module>
    from HorribleDownloader.cmd import cli
  File "/usr/local/lib/python3.5/dist-packages/HorribleDownloader/cmd.py", line 99
    subprocess.call(f"webtorrent \"{episode[quality]['Magnet']}\" -o \"{subdir}\"", shell=True)
                                                                                 ^
as soon as I haven’t tried, it doesn’t work( python 3.5

**Comment by baxa73** [comment]
the strangest thing, a few days ago everything worked) as I reinstalled it, it stopped

**Comment by mtshrmn** [comment]
This shouldn't work with python 3.5, string literals are supported only from 3.6.

Are you sure it was running on python 3.5 beforehand?

**Comment by baxa73** [comment]
> This shouldn't work with python 3.5, string literals are supported only from 3.6.
> 
> Are you sure it was running on python 3.5 beforehand?

Thank you very much) it helped!) in the beginning I  set 3.7, later 3.5, but it did not work.. but you really helped me)
