### ISSUE TITLE
get_episodes(show: str, limit) is not limiting the correct number of episodes

### ISSUE THREAD

**Issue by allansoria** [Jelomite/horrible-downloader#24]
The limit parameter not returning the number assigned. Returning multiples of 12 episodes. 

Ex1: get_episodes('show', limit=1)   =>   12 episodes
Ex2: get_episodes('show', limit=13) => 24 episodes

**Comment by mtshrmn** [comment]
I've fixed the behavior, and updated the documentation to be more accurate. Thank you for submitting this issue, and sorry for the delay.
