### ISSUE TITLE
UnicodeDecodeError: 'charmap'

### ISSUE THREAD

**Issue by cdrakke** [Jelomite/horrible-downloader#25]
C:\Users\Calvi>pip install horrible-downloader
Collecting horrible-downloader
  Using cached horrible-downloader-1.0.4.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\calvi\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Calvi\\AppData\\Local\\Temp\\pip-install-3348u_dx\\horrible-downloader\\setup.py'"'"'; __file__='"'"'C:\\Users\\Calvi\\AppData\\Local\\Temp\\pip-install-3348u_dx\\horrible-downloader\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Calvi\AppData\Local\Temp\pip-install-3348u_dx\horrible-downloader\pip-egg-info'
         cwd: C:\Users\Calvi\AppData\Local\Temp\pip-install-3348u_dx\horrible-downloader\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Calvi\AppData\Local\Temp\pip-install-3348u_dx\horrible-downloader\setup.py", line 7, in <module>
        long_description = f.read()
      File "c:\users\calvi\appdata\local\programs\python\python38-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5415: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by cdrakke** [comment]
I found a solution myself but idk if its even decent or just plain bad lmao

! Make sure you have node installed.

-> Clone or download the repo
-> Extract it and open cmd then cd to that directory
-> Edit setup.py 

FROM: 
```py
with open("README.md", 'r') as f:
    long_description = f.read()
```

TO:
```py
with open("README.md", 'r', encoding='utf-8') as f:
    long_description = f.read()
```

-> Now go back to the cmd. Be sure that its directory is where you can access setup.py
-> Run python setup.py install

It will have an error: Warning: 'classifiers' should be a list, got type 'tuple'
But it will still install.
I think the creator should update it.

**Comment by mtshrmn** [comment]
Thank you for submitting this issue. It's already a known issue. (see #22).
I've been working on this today, please expect a new version to come out today and fix the problem.
