### ISSUE TITLE
Error webtorrent not found

### ISSUE THREAD

**Issue by ShalmonAnandas** [Jelomite/horrible-downloader#41]
FETCHING: One-Punch Man.....................................FOUND (3)

Found 3 files to download:

One-Punch Man - 03 [1080p].mkv
One-Punch Man - 02 [1080p].mkv
One-Punch Man - 01 [1080p].mkv

would you like to proceed? [Y/n] y
/bin/sh: 1: webtorrent: not found
/bin/sh: 1: webtorrent: not found
/bin/sh: 1: webtorrent: not found
shalmon@shalmon-MS-7B38:~$ horrible-downloader -d "one punch man" -e 1,2,3, -o ~/media/shalmon/Shalmon/

**Comment by mtshrmn** [comment]
Please install webtorrent by the following command: `npm install webtorrent-cli -g`
