### ISSUE TITLE
Limit not working properly

### ISSUE THREAD

**Issue by Gbd199** [Jelomite/horrible-downloader#50]
![image](https://user-images.githubusercontent.com/28998404/89710445-d4144080-d98b-11ea-8563-f8c9d81aceb0.png)

If the limit is below 12, the function returns an empty list, for anything between 12-24 it returns 12 and so on.

The solution is simply changing the '>=' to '>' in:
https://github.com/mtshrmn/horrible-downloader/blob/eb6bec5321de6ba5f25e05663d357185c8183f1e/HorribleDownloader/parser.py#L87

I will submit a pull request but wanted to get feedback first in case I'm missing something.

Python 3.8.2, latest version of the package

**Comment by mtshrmn** [comment]
The code is working as intended, although the documentation around it is misleading (so it seems). I think that changing the limit behavior is appropriate. 

Your solution is almost correct, but I'll elaborate in the PR.
