### ISSUE TITLE
change title fuzzing scorer for better results

### ISSUE THREAD

**Issue by Gbd199** [Jelomite/horrible-downloader#52]
The scorer currently used is the default WRation one, it returns dissatisfying results. 
f.e for "enen s2" it returned "Ace Attorney S2" instead of the expected "Enen no Shouboutai S2".

I did some reading on https://medium.com/analytics-vidhya/matching-messy-pandas-columns-with-fuzzywuzzy-4adda6c7994f and experimented a bit, and found that the best resulting fuzzing scorer is 'token_set_ratio', which returns way better results and even works faster.
 
The change is simply adding `scorer=fuzz.token_set_ratio`(after importing fuzz from rapidfuzz of course) to:
https://github.com/mtshrmn/horrible-downloader/blob/eb6bec5321de6ba5f25e05663d357185c8183f1e/HorribleDownloader/parser.py#L21

**Comment by mtshrmn** [comment]
I've experienced similar problems, but dismissed it because I thought this was the best fuzzy string matching algorithm without even checking. Thank you for improving it.
