### ISSUE TITLE
Add support for local torrent client or exporting magnet links

### ISSUE THREAD

**Issue by aTosser** [Jelomite/horrible-downloader#54]
Would it be possible to add an option to print to stdout the magnet links so they could be added to the local torrent client?

**Comment by mtshrmn** [comment]
The whole problem here is that once you pass it to an external torrent client, I have no way of knowing if the file has actually finished downloading. For your implementation it seems that once you pass the magnet it's considered as downloaded. I'm not very keen about this. But as it's the a very simple implementation, I'll approve it.

**Comment by aTosser** [comment]
The idea is that, this could be used in a wrapper script to redirect to any client you choose. The reason for this approach was in my niche case I do not use an application local to my computer but a web interface and so outputting the magnet links allows for me to simply copy and paste into the web interface but also still allow anyone else to pipe the output to another application directly.
